export const {
  PORT = 4000,
  NODE_ENV = 'development',
  R2_ACCOUNT_ID = '***',
  R2_ACCESS_KEY_ID = '***',
  R2_SECRET_ACCESS_KEY = '***',
  R2_BUCKET_NAME = '***',
  AUTH_JWT_SECRET = '***',
  R2_URL = null,
  AUTH_JWT_REFRESH_SECRET = '***',
  AUTH_HEADER = 'authorization',
  AUTH_EXPIRES_IN = '14d',
} = process.env
